name: cli test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pulling code
        uses: actions/checkout@v1

      - name: setting up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6

      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install sathya
        run:  python setup.py install

      - name: test help
        run: sathya --help
